import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

describe("SEO evidence artifact validation", () => {
  it("exposes a local validator for uploaded production SEO evidence files", () => {
    const packageJson = JSON.parse(fs.readFileSync(path.join(process.cwd(), "package.json"), "utf8")) as {
      scripts: Record<string, string>;
    };
    const script = fs.readFileSync(path.join(process.cwd(), "scripts/validate-seo-evidence.mjs"), "utf8");
    const structuredDataScript = fs.readFileSync(
      path.join(process.cwd(), "scripts/structured-data-evidence.mjs"),
      "utf8",
    );
    const workflow = fs.readFileSync(path.join(process.cwd(), ".github/workflows/seo-smoke.yml"), "utf8");
    const manifestScript = fs.readFileSync(path.join(process.cwd(), "scripts/generate-seo-evidence-manifest.mjs"), "utf8");

    expect(packageJson.scripts["seo:evidence-validate"]).toBe("node scripts/validate-seo-evidence.mjs");
    expect(packageJson.scripts["seo:evidence-manifest"]).toBe("node scripts/generate-seo-evidence-manifest.mjs");
    expect(packageJson.scripts["seo:performance"]).toBe("node scripts/performance-evidence.mjs");
    expect(packageJson.scripts["seo:structured-data"]).toBe("node scripts/structured-data-evidence.mjs");
    expect(script).toContain("seo-smoke-result.json");
    expect(script).toContain("gsc-evidence-result.json");
    expect(script).toContain("performance-evidence-result.json");
    expect(script).toContain("structured-data-evidence-result.json");
    expect(script).toContain("blog-discovery-evidence-result.json");
    expect(script).toContain("fileURLToPath(import.meta.url)");
    expect(script).toContain("lastmodFresh");
    expect(script).toContain("priorityUrlCount");
    expect(script).toContain("hasUtf16Bom");
    expect(script).toContain("utf16le");
    expect(script).toContain("/seo-monitoring");
    expect(script).toContain("/tax-brackets/2026");
    expect(script).toContain("validateStructuredDataEvidence");
    expect(script).toContain("validateBlogDiscoveryEvidence");
    expect(script).toContain("validatePerformanceEvidence");
    expect(script).toContain("lighthouse-mobile-lab");
    expect(script).toContain("performanceScore");
    expect(script).toContain("thresholdResults");
    expect(script).toContain("manualReviewRequired");
    expect(script).toContain("blogDiscoveryCount");
    expect(script).toContain("structuredDataTypeCount");
    expect(script).toContain("pageCount");
    expect(script).toContain("STATIC_STRUCTURED_DATA_PAGE_COUNT");
    expect(script).toContain("readBlogSlugCount");
    expect(script).toContain("expectedStructuredDataPageCount");
    expect(script).toContain("/roth-conversion-irmaa-guide");
    expect(script).toContain("/roth-conversion-aca-premium-tax-credit-guide");
    expect(script).toContain("/roth-conversion-niit-guide");
    expect(script).toContain("/roth-conversion-rmd-guide");
    expect(script).toContain("/roth-conversion-social-security-tax-guide");
    expect(script).toContain("/roth-conversion-estimated-tax-guide");
    expect(script).toContain("/calculator-assumptions-guide");
    expect(script).toContain("/cpa-review-checklist");
    expect(script).toContain("/roth-conversion-tax-forms");
    expect(script).toContain("/roth-conversion-timeline");
    expect(script).toContain("must contain a single JSON object");
    expect(structuredDataScript).toContain("STRUCTURED_DATA_EVIDENCE_BASE_URL");
    expect(structuredDataScript).toContain("WebApplication");
    expect(structuredDataScript).toContain("WebSite");
    expect(structuredDataScript).toContain("WebPage");
    expect(structuredDataScript).toContain("HowTo");
    expect(structuredDataScript).toContain("Organization");
    expect(structuredDataScript).toContain("FAQPage");
    expect(structuredDataScript).toContain("aggregateRating");
    expect(structuredDataScript).toContain("reviewRating");
    expect(structuredDataScript).toContain("100%\\s+accurate");
    expect(structuredDataScript).toContain("voiceInput");
    expect(structuredDataScript).toContain("siteUrlCount");
    expect(structuredDataScript).toContain("monitoredPages");
    expect(structuredDataScript).toContain("/roth-conversion-irmaa-guide");
    expect(structuredDataScript).toContain("/roth-conversion-aca-premium-tax-credit-guide");
    expect(structuredDataScript).toContain("/tax-brackets/2026");
    expect(structuredDataScript).toContain("/roth-conversion-niit-guide");
    expect(structuredDataScript).toContain("/roth-conversion-rmd-guide");
    expect(structuredDataScript).toContain("/roth-conversion-social-security-tax-guide");
    expect(structuredDataScript).toContain("/roth-conversion-estimated-tax-guide");
    expect(structuredDataScript).toContain("/calculator-assumptions-guide");
    expect(structuredDataScript).toContain("/cpa-review-checklist");
    expect(structuredDataScript).toContain("/roth-conversion-tax-forms");
    expect(structuredDataScript).toContain("/roth-conversion-timeline");
    expect(structuredDataScript).toContain("src/content/blog.ts");
    expect(structuredDataScript).toContain("fileURLToPath(import.meta.url)");
    expect(structuredDataScript).toContain("readBlogArticlePages");
    expect(structuredDataScript).toContain('path: `/blog/${slug}`');
    expect(structuredDataScript).toContain("Article");
    expect(structuredDataScript).toContain("BreadcrumbList");
    expect(workflow).toContain("Run structured data evidence check");
    expect(workflow).toContain("Run mobile performance evidence check");
    expect(workflow).toContain("set -o pipefail");
    expect(workflow).toContain("node scripts/performance-evidence.mjs | tee performance-evidence-result.json");
    expect(workflow).toContain("node scripts/structured-data-evidence.mjs | tee structured-data-evidence-result.json");
    expect(workflow).toContain("Run blog discovery evidence check");
    expect(workflow).toContain("node scripts/blog-discovery-evidence.mjs | tee blog-discovery-evidence-result.json");
    expect(workflow).toContain("Validate SEO evidence artifact");
    expect(workflow).toContain("node scripts/validate-seo-evidence.mjs | tee seo-evidence-validation-result.json");
    expect(workflow).toContain("Generate SEO evidence manifest");
    expect(workflow).toContain("node scripts/generate-seo-evidence-manifest.mjs | tee seo-evidence-manifest.json");
    expect(manifestScript).toContain("structured-data-evidence-result.json");
    expect(manifestScript).toContain("performance-evidence-result.json");
    expect(manifestScript).toContain("blog-discovery-evidence-result.json");
    expect(manifestScript).toContain("GITHUB_RUN_ID");
    expect(manifestScript).toContain("GITHUB_SHA");
    expect(manifestScript).toContain("hasUtf16Bom");
    expect(manifestScript).toContain("utf16le");
    expect(manifestScript).toContain("selfDescribing");
    expect(manifestScript).toContain("seo-evidence-manifest.json");
    expect(manifestScript).toContain("production-seo-evidence");
    expect(manifestScript).toContain("retentionDays: 30");
  });

  it("keeps the uploaded artifact files aligned with validator defaults", () => {
    const workflow = fs.readFileSync(path.join(process.cwd(), ".github/workflows/seo-smoke.yml"), "utf8");

    expect(workflow).toContain("node scripts/seo-smoke.mjs | tee seo-smoke-result.json");
    expect(workflow).toContain("node scripts/gsc-evidence.mjs | tee gsc-evidence-result.json");
    expect(workflow).toContain("node scripts/performance-evidence.mjs | tee performance-evidence-result.json");
    expect(workflow).toContain("node scripts/structured-data-evidence.mjs | tee structured-data-evidence-result.json");
    expect(workflow).toContain("node scripts/blog-discovery-evidence.mjs | tee blog-discovery-evidence-result.json");
    expect(workflow).toContain("node scripts/validate-seo-evidence.mjs | tee seo-evidence-validation-result.json");
    expect(workflow).toContain("node scripts/generate-seo-evidence-manifest.mjs | tee seo-evidence-manifest.json");
    expect(workflow).toContain("seo-smoke-result.json");
    expect(workflow).toContain("gsc-evidence-result.json");
    expect(workflow).toContain("performance-evidence-result.json");
    expect(workflow).toContain("structured-data-evidence-result.json");
    expect(workflow).toContain("blog-discovery-evidence-result.json");
    expect(workflow).toContain("seo-evidence-validation-result.json");
    expect(workflow).toContain("seo-evidence-manifest.json");
    expect(workflow).toContain("name: production-seo-evidence");
    expect(workflow).toContain("retention-days: 30");
  });
});
