export type FeatureLayer = "core" | "common" | "feature" | "content";

export interface FeatureRegistryItem {
  id: string;
  label: string;
  version: string;
  layer: FeatureLayer;
  enabled: boolean;
  locked: boolean;
  grayRate: number;
  ownerArea: string;
  rollbackPath: string;
}

export const featureRegistry: FeatureRegistryItem[] = [
  {
    id: "core-calculator",
    label: "Core Roth conversion calculator",
    version: "1.0.0",
    layer: "core",
    enabled: true,
    locked: true,
    grayRate: 100,
    ownerArea: "src/core/calculator",
    rollbackPath: "Core changes require reviewed release rollback, not feature-level shutdown.",
  },
  {
    id: "ai-explainer",
    label: "AI Roth Conversion Explainer",
    version: "1.0.171",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/ai-assistant",
    rollbackPath: "Remove AiExplainer from the homepage and keep the calculator available, or restore the previous support-panel copy and classes.",
  },
  {
    id: "scenario-history",
    label: "Saved scenarios",
    version: "1.0.2",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/scenario-history",
    rollbackPath: "Remove ScenarioHistoryPanel from the results card.",
  },
  {
    id: "state-tax-shortcuts",
    label: "State tax shortcuts",
    version: "1.0.3",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/calculator-input",
    rollbackPath: "Hide the state shortcut selector and keep manual state tax input.",
  },
  {
    id: "calculator-input-layout",
    label: "Calculator input layout",
    version: "1.0.147",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/calculator-input",
    rollbackPath:
      "Restore retirement age and expected annual return to the always-visible Quick Estimate field list and remove the enhanced disclosure summary treatment.",
  },
  {
    id: "theme-toggle",
    label: "Light and dark mode toggle",
    version: "1.0.4",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/theme-toggle",
    rollbackPath: "Remove ThemeToggle from the top navigation.",
  },
  {
    id: "copy-summary",
    label: "Copy summary",
    version: "1.0.5",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/result-copy",
    rollbackPath: "Remove CopyResultButton from the results actions.",
  },
  {
    id: "share-link",
    label: "Share result link",
    version: "1.0.179",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/share-link, src/common/storage/share-code, and src/app/HomeCalculatorClient.tsx",
    rollbackPath:
      "Disable share-link in the feature registry, remove ShareResultButton from the homepage result actions, and keep local calculator persistence available.",
  },
  {
    id: "pdf-report",
    label: "Print-ready report export",
    version: "1.0.178",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/pdf-report and src/app/HomeCalculatorClient.tsx",
    rollbackPath:
      "Disable pdf-report in the feature registry, remove PdfReportButton from the homepage result actions, or restore the prior report export implementation.",
  },
  {
    id: "professional-handoff",
    label: "CPA packet copy action",
    version: "1.0.180",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/professional-handoff and src/app/HomeCalculatorClient.tsx",
    rollbackPath:
      "Disable professional-handoff in the feature registry, remove CopyProfessionalHandoffButton from the homepage result actions, and keep the professional review packet page available.",
  },
  {
    id: "projection-chart",
    label: "Projection chart",
    version: "1.0.181",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/charts and src/app/HomeCalculatorClient.tsx",
    rollbackPath:
      "Disable projection-chart in the feature registry and remove the homepage Projection card while keeping numerical result estimates available.",
  },
  {
    id: "calculation-breakdown",
    label: "Advanced calculation breakdown",
    version: "1.0.182",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/calculation-breakdown and src/app/HomeCalculatorClient.tsx",
    rollbackPath:
      "Disable calculation-breakdown in the feature registry and remove the homepage Advanced calculation details disclosure while keeping summary estimates, projection, and professional handoff available.",
  },
  {
    id: "tax-payment-comparison",
    label: "Tax payment method comparison",
    version: "1.0.183",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/tax-payment-comparison and src/app/HomeCalculatorClient.tsx",
    rollbackPath:
      "Disable tax-payment-comparison in the feature registry and remove the homepage Tax Payment Method Comparison panel while keeping result summary, warnings, projection, and professional handoff available.",
  },
  {
    id: "result-scope-boundary",
    label: "Result scope and tax-advice boundary",
    version: "1.0.184",
    layer: "feature",
    enabled: true,
    locked: true,
    grayRate: 100,
    ownerArea: "src/features/result-scope and src/app/HomeCalculatorClient.tsx",
    rollbackPath:
      "Locked YMYL boundary: do not disable through feature flags. Any rollback must keep equivalent visible tax-year, educational-estimate, input-based, and not-tax-advice boundary copy before the result summary.",
  },
  {
    id: "tax-impact-warnings-boundary",
    label: "Tax impact warnings boundary",
    version: "1.0.202",
    layer: "feature",
    enabled: true,
    locked: true,
    grayRate: 100,
    ownerArea: "src/features/tax-impact-warnings and src/app/HomeCalculatorClient.tsx",
    rollbackPath:
      "Locked YMYL boundary: do not disable through feature flags. Any rollback must keep equivalent visible IRMAA, ACA, Social Security, NIIT, RMD, and state-tax review warnings near the result summary.",
  },
  {
    id: "faq-schema",
    label: "FAQPage structured data",
    version: "1.0.6",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/faq",
    rollbackPath: "Remove faqJsonLd from the homepage scripts.",
  },
  {
    id: "state-prefill-links",
    label: "State-rate calculator prefill links",
    version: "1.0.7",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/app/states/[state]",
    rollbackPath: "Change state CTA href back to /#calculator.",
  },
  {
    id: "tax-data-freshness",
    label: "Tax data freshness card",
    version: "1.0.8",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/tax-data-freshness",
    rollbackPath: "Remove TaxDataFreshnessCard mount points.",
  },
  {
    id: "conversion-sensitivity",
    label: "Conversion sensitivity table",
    version: "1.0.9",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/conversion-sensitivity",
    rollbackPath: "Remove ConversionSensitivityTable from the homepage results area.",
  },
  {
    id: "bracket-capacity",
    label: "Federal bracket capacity table",
    version: "1.0.10",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/bracket-capacity",
    rollbackPath: "Remove FederalBracketCapacityTable from the homepage results area.",
  },
  {
    id: "multi-year-schedule",
    label: "Multi-year conversion schedule",
    version: "1.0.11",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/multi-year-schedule",
    rollbackPath: "Remove MultiYearScheduleTable from the homepage results area.",
  },
  {
    id: "ai-compliance-gateway",
    label: "AI compliance gateway and rate limit",
    version: "1.0.173",
    layer: "common",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/core/compliance and src/core/ai",
    rollbackPath: "Route AI requests back through the previous ai-guardrails-only flow and disable the rate-limit wrapper.",
  },
  {
    id: "irmaa-review-prep",
    label: "IRMAA review prep",
    version: "1.0.175",
    layer: "feature",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/features/tax-impact-warnings and src/features/professional-handoff",
    rollbackPath:
      "Remove the IRMAA review-prep helper, remove the result-panel IRMAA prep section, and remove the IRMAA prep lines from the CPA packet while keeping the standard IRMAA guide available.",
  },
  {
    id: "seo-structured-content",
    label: "Article, breadcrumb, and long-tail content matrix",
    version: "1.0.124",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/core/seo, src/content/blog, src/app/blog, src/app/states",
    rollbackPath:
      "Restore previous SEO metadata and siteName values, then remove the homepage WebSite/WebPage JSON-LD additions, Article/Breadcrumb JSON-LD scripts, and related structured-content tests if needed.",
  },
  {
    id: "production-readiness",
    label: "Production security headers and E2E readiness checks",
    version: "1.0.14",
    layer: "common",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "next.config.ts and tests/e2e",
    rollbackPath: "Remove the global security headers and operational readiness Playwright spec.",
  },
  {
    id: "privacy-safe-analytics",
    label: "Privacy-safe GA4 analytics",
    version: "1.0.117",
    layer: "common",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/core/analytics and src/features/analytics",
    rollbackPath: "Remove GoogleAnalytics from the root layout and CalculatorAnalyticsBeacon from the homepage.",
  },
  {
    id: "blog-internal-linking",
    label: "Blog topic hub and related guide links",
    version: "1.0.135",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/blog and src/app/blog",
    rollbackPath:
      "Restore the previous blog shell surface classes or remove topic groups, related guide rendering, and calculator CTA from blog pages.",
  },
  {
    id: "search-console-verification",
    label: "Google Search Console verification metadata",
    version: "1.0.17",
    layer: "common",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/core/seo/search-console and src/app/layout.tsx",
    rollbackPath: "Remove metadata.verification from the root layout and unset NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION.",
  },
  {
    id: "rss-feed",
    label: "Blog RSS feed",
    version: "1.0.18",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/core/seo/rss and src/app/feed.xml",
    rollbackPath: "Remove the feed.xml route and feed.xml entry from robots metadata.",
  },
  {
    id: "homepage-lazy-loading",
    label: "Homepage lazy loading for non-critical modules",
    version: "1.0.126",
    layer: "common",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/app/page.tsx and src/app/HomeCalculatorClient.tsx",
    rollbackPath:
      "Restore the previous homepage hero, calculator split, shared primitive visual classes, result summary styling, and result action loading behavior while keeping the client island boundary intact.",
  },
  {
    id: "glossary-hub",
    label: "Roth conversion glossary hub",
    version: "1.0.20",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/glossary and src/app/glossary",
    rollbackPath: "Remove glossary routes, glossary sitemap entries, and homepage glossary links.",
  },
  {
    id: "health-check-endpoint",
    label: "Operational health check endpoint",
    version: "1.0.21",
    layer: "common",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/core/ops and src/app/api/health",
    rollbackPath: "Remove the api/health route and health payload builder.",
  },
  {
    id: "federal-tax-brackets-page",
    label: "2026 federal tax brackets reference page",
    version: "1.0.22",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/app/tax-brackets/2026 and src/core/tax-data",
    rollbackPath: "Remove the tax-brackets/2026 route, sitemap entry, and homepage navigation links.",
  },
  {
    id: "filing-status-seo-pages",
    label: "Filing status Roth conversion SEO pages",
    version: "1.0.23",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/filing-status-pages and src/app/filing-status",
    rollbackPath: "Remove filing-status routes, content model, and sitemap entries.",
  },
  {
    id: "filing-status-hub",
    label: "Filing status SEO hub",
    version: "1.0.24",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/app/filing-status and src/app/page.tsx",
    rollbackPath: "Remove the /filing-status hub route, sitemap entry, and homepage links while keeping detail pages available.",
  },
  {
    id: "age-scenario-seo-pages",
    label: "Age scenario Roth conversion SEO pages",
    version: "1.0.25",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/age-scenario-pages and src/app/age-scenarios",
    rollbackPath: "Remove age-scenarios routes, sitemap entries, homepage links, and the age scenario content model.",
  },
  {
    id: "example-scenario-seo-pages",
    label: "Example scenario SEO pages",
    version: "1.0.26",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/example-scenario-pages and src/app/examples",
    rollbackPath: "Remove examples routes, sitemap entries, homepage links, and the example scenario content model.",
  },
  {
    id: "homepage-howto-structured-data",
    label: "Homepage structured data",
    version: "1.0.89",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/core/seo/json-ld and src/app/page.tsx",
    rollbackPath:
      "Disable homepage-howto-structured-data in the feature registry or remove the WebSite, WebPage, HowTo, and Organization JSON-LD scripts from the homepage.",
  },
  {
    id: "pwa-install-icons",
    label: "PWA install icons",
    version: "1.0.28",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/app/manifest.ts and src/app/icon.svg",
    rollbackPath: "Disable pwa-install-icons in the feature registry and remove manifest icon entries and generated SVG icon assets.",
  },
  {
    id: "keyword-landing-pages",
    label: "Core keyword landing pages",
    version: "1.0.29",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/keyword-landing-pages and src/app/(keyword-pages)",
    rollbackPath: "Disable keyword-landing-pages in the feature registry and remove calculator keyword routes, sitemap entries, and homepage links.",
  },
  {
    id: "social-preview-metadata",
    label: "Social preview metadata",
    version: "1.0.30",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/app/layout.tsx",
    rollbackPath: "Disable social-preview-metadata in the feature registry and remove twitter metadata from the root layout.",
  },
  {
    id: "tax-bracket-rate-pages",
    label: "Tax bracket rate SEO pages",
    version: "1.0.31",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/tax-bracket-rate-pages and src/app/tax-brackets/2026/[rate]",
    rollbackPath: "Disable tax-bracket-rate-pages in the feature registry and remove rate routes, sitemap entries, and bracket-index links.",
  },
  {
    id: "sitemap-priority-hints",
    label: "Sitemap priority hints",
    version: "1.0.77",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/app/sitemap.ts",
    rollbackPath: "Disable sitemap-priority-hints in the feature registry and remove priority/changeFrequency fields from sitemap entries.",
  },
  {
    id: "tax-payment-method-pages",
    label: "Tax payment method SEO pages",
    version: "1.0.33",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/tax-payment-method-pages and src/app/tax-payment-methods",
    rollbackPath: "Disable tax-payment-method-pages in the feature registry and remove tax-payment-method routes, sitemap entries, and homepage links.",
  },
  {
    id: "basis-planning-pages",
    label: "Basis planning SEO pages",
    version: "1.0.34",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/basis-planning-pages and src/app/basis",
    rollbackPath: "Disable basis-planning-pages in the feature registry and remove basis routes, sitemap entries, and homepage links.",
  },
  {
    id: "llms-text-index",
    label: "LLM text index",
    version: "1.0.35",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/core/seo/llms and src/app/llms.txt",
    rollbackPath: "Disable llms-text-index in the feature registry and remove the llms.txt route plus robots metadata entry.",
  },
  {
    id: "social-preview-image",
    label: "Social preview image",
    version: "1.0.36",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/app/layout.tsx and src/app/social-preview.svg",
    rollbackPath: "Disable social-preview-image in the feature registry and remove social image metadata plus the local SVG asset.",
  },
  {
    id: "multi-year-planning-pages",
    label: "Multi-year planning SEO pages",
    version: "1.0.37",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/multi-year-planning-pages and src/app/multi-year-planning",
    rollbackPath: "Disable multi-year-planning-pages in the feature registry and remove multi-year planning routes, sitemap entries, and homepage links.",
  },
  {
    id: "roth-conversion-qcd-guide",
    label: "Roth conversion QCD guide",
    version: "1.0.67",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/qcd-guide and src/app/roth-conversion-qcd-guide",
    rollbackPath:
      "Disable roth-conversion-qcd-guide in the feature registry and remove the QCD guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-recharacterization-guide",
    label: "Roth conversion recharacterization guide",
    version: "1.0.66",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/recharacterization-guide and src/app/roth-conversion-recharacterization-guide",
    rollbackPath:
      "Disable roth-conversion-recharacterization-guide in the feature registry and remove the recharacterization guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-estimated-tax-guide",
    label: "Roth conversion estimated tax guide",
    version: "1.0.65",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/estimated-tax-guide and src/app/roth-conversion-estimated-tax-guide",
    rollbackPath:
      "Disable roth-conversion-estimated-tax-guide in the feature registry and remove the estimated tax guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-capital-gains-guide",
    label: "Roth conversion capital gains guide",
    version: "1.0.64",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/capital-gains-guide and src/app/roth-conversion-capital-gains-guide",
    rollbackPath:
      "Disable roth-conversion-capital-gains-guide in the feature registry and remove the capital gains guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-niit-guide",
    label: "Roth conversion NIIT guide",
    version: "1.0.63",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/niit-guide and src/app/roth-conversion-niit-guide",
    rollbackPath:
      "Disable roth-conversion-niit-guide in the feature registry and remove the NIIT guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-aca-premium-tax-credit-guide",
    label: "Roth conversion ACA premium tax credit guide",
    version: "1.0.62",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea:
      "src/content/aca-premium-tax-credit-guide and src/app/roth-conversion-aca-premium-tax-credit-guide",
    rollbackPath:
      "Disable roth-conversion-aca-premium-tax-credit-guide in the feature registry and remove the ACA premium tax credit guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-irmaa-guide",
    label: "Roth conversion IRMAA guide",
    version: "1.0.61",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/irmaa-guide and src/app/roth-conversion-irmaa-guide",
    rollbackPath:
      "Disable roth-conversion-irmaa-guide in the feature registry and remove the IRMAA guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-social-security-tax-guide",
    label: "Roth conversion Social Security tax guide",
    version: "1.0.60",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/social-security-tax-guide and src/app/roth-conversion-social-security-tax-guide",
    rollbackPath:
      "Disable roth-conversion-social-security-tax-guide in the feature registry and remove the Social Security tax guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-rmd-guide",
    label: "Roth conversion RMD guide",
    version: "1.0.59",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/rmd-guide and src/app/roth-conversion-rmd-guide",
    rollbackPath:
      "Disable roth-conversion-rmd-guide in the feature registry and remove the RMD guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-five-year-rules-guide",
    label: "Roth conversion 5-year rules guide",
    version: "1.0.58",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/five-year-rules-guide and src/app/roth-conversion-5-year-rules",
    rollbackPath:
      "Disable roth-conversion-five-year-rules-guide in the feature registry and remove the 5-year rules route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-cpa-questions-guide",
    label: "Roth conversion CPA questions guide",
    version: "1.0.57",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/cpa-questions-guide and src/app/roth-conversion-cpa-questions",
    rollbackPath:
      "Disable roth-conversion-cpa-questions-guide in the feature registry and remove the CPA questions route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-custodian-process-guide",
    label: "Roth conversion custodian process guide",
    version: "1.0.56",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/custodian-process-guide and src/app/roth-conversion-custodian-process",
    rollbackPath:
      "Disable roth-conversion-custodian-process-guide in the feature registry and remove the custodian process guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-timeline-guide",
    label: "Roth conversion timeline guide",
    version: "1.0.55",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/timeline-guide and src/app/roth-conversion-timeline",
    rollbackPath:
      "Disable roth-conversion-timeline-guide in the feature registry and remove the timeline guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-tax-forms-guide",
    label: "Roth conversion tax forms guide",
    version: "1.0.54",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/tax-forms-guide and src/app/roth-conversion-tax-forms",
    rollbackPath:
      "Disable roth-conversion-tax-forms-guide in the feature registry and remove the tax forms guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-mistakes-guide",
    label: "Roth conversion mistakes guide",
    version: "1.0.53",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/common-mistakes-guide and src/app/roth-conversion-mistakes",
    rollbackPath:
      "Disable roth-conversion-mistakes-guide in the feature registry and remove the mistakes guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "calculator-assumptions-guide",
    label: "Calculator assumptions guide",
    version: "1.0.52",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/calculator-assumptions-guide and src/app/calculator-assumptions-guide",
    rollbackPath:
      "Disable calculator-assumptions-guide in the feature registry and remove the assumptions guide route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "roth-conversion-planning-checklist",
    label: "Roth conversion planning checklist",
    version: "1.0.51",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/planning-checklist and src/app/roth-conversion-planning-checklist",
    rollbackPath:
      "Disable roth-conversion-planning-checklist in the feature registry and remove the planning checklist route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "privacy-data-flow-playbook",
    label: "Privacy data flow playbook",
    version: "1.0.50",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/privacy-data-flow and src/app/privacy-data-flow",
    rollbackPath:
      "Disable privacy-data-flow-playbook in the feature registry and remove the privacy-data-flow route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "feedback-roadmap-playbook",
    label: "Feedback roadmap playbook",
    version: "1.0.49",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/feedback-roadmap and src/app/feedback-roadmap",
    rollbackPath:
      "Disable feedback-roadmap-playbook in the feature registry and remove the feedback-roadmap route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "cpa-review-checklist",
    label: "CPA review checklist",
    version: "1.0.156",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea:
      "src/content/cpa-review-checklist, src/content/professional-review-packet, src/app/cpa-review-checklist, and src/app/professional-review-packet",
    rollbackPath:
      "Disable cpa-review-checklist in the feature registry and remove the cpa-review-checklist and professional-review-packet routes, sitemap entries, homepage links, site-index links, and llms.txt links.",
  },
  {
    id: "content-operations-playbook",
    label: "Content operations playbook",
    version: "1.0.106",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/content-operations and src/app/content-operations",
    rollbackPath:
      "Disable content-operations-playbook in the feature registry and remove the content-operations route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "operations-page-ui",
    label: "Professional operations page UI",
    version: "1.0.134",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea:
      "src/app/seo-monitoring, src/app/content-operations, src/app/performance-audit, and related operations playbook routes",
    rollbackPath:
      "Restore the previous glass and large-radius operations page container classes, then remove the operations-page UI regression guard.",
  },
  {
    id: "content-hub-page-ui",
    label: "Professional content hub page UI",
    version: "1.0.130",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea:
      "src/app/site-index, src/app/release-notes, and top-level content hub routes",
    rollbackPath:
      "Restore the previous translucent and large-radius hub page card classes, then remove the content-hub UI regression guard.",
  },
  {
    id: "priority-guide-page-ui",
    label: "Professional priority guide page UI",
    version: "1.0.131",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea:
      "src/app/calculator-assumptions-guide, src/app/cpa-review-checklist, and Roth conversion priority guide routes",
    rollbackPath:
      "Restore the previous translucent, large-radius, and heavy-shadow guide page container classes, then remove the priority-guide UI regression guard.",
  },
  {
    id: "dynamic-detail-page-ui",
    label: "Professional dynamic detail page UI",
    version: "1.0.132",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea:
      "src/app/(keyword-pages), dynamic content detail routes, and 2026 federal bracket detail routes",
    rollbackPath:
      "Restore the previous translucent, large-radius, and heavy-shadow dynamic detail page container classes, then remove the dynamic-detail UI regression guard.",
  },
  {
    id: "shared-feature-ui",
    label: "Professional shared feature component UI",
    version: "1.0.133",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea:
      "src/features shared calculator, methodology, FAQ, scenario history, theme, and tax-data surfaces",
    rollbackPath:
      "Restore the previous translucent, glass, large-radius, and heavy-shadow shared feature component classes, then remove the shared-feature UI regression guard.",
  },
  {
    id: "professional-ui-global-guard",
    label: "Global professional UI guard",
    version: "1.0.137",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/app, src/features, and tests/core/professional-ui-global-guard.test.ts",
    rollbackPath:
      "Remove the global professional UI guard test and professional UI evidence artifact wiring if the app intentionally adopts a new approved surface system.",
  },
  {
    id: "ai-compliance-audit-playbook",
    label: "AI compliance audit playbook",
    version: "1.0.46",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/ai-compliance-audit and src/app/ai-compliance-audit",
    rollbackPath:
      "Disable ai-compliance-audit-playbook in the feature registry and remove the ai-compliance-audit route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "tax-data-update-playbook",
    label: "Tax data update playbook",
    version: "1.0.45",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/tax-data-update and src/app/tax-data-update",
    rollbackPath:
      "Disable tax-data-update-playbook in the feature registry and remove the tax-data-update route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "accessibility-audit-playbook",
    label: "Accessibility audit playbook",
    version: "1.0.44",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/accessibility-audit and src/app/accessibility-audit",
    rollbackPath:
      "Disable accessibility-audit-playbook in the feature registry and remove the accessibility-audit route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "performance-audit-playbook",
    label: "Performance audit playbook",
    version: "1.0.122",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/performance-audit and src/app/performance-audit",
    rollbackPath:
      "Disable performance-audit-playbook in the feature registry and remove the performance-audit route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "seo-monitoring-playbook",
    label: "SEO monitoring playbook",
    version: "1.0.174",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/seo-monitoring and src/app/seo-monitoring",
    rollbackPath:
      "Disable seo-monitoring-playbook in the feature registry and remove the seo-monitoring route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "production-launch-guide",
    label: "Production launch guide",
    version: "1.0.41",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/production-launch and src/app/production-launch",
    rollbackPath:
      "Disable production-launch-guide in the feature registry and remove the production-launch route, sitemap entry, homepage link, site-index link, and llms.txt link.",
  },
  {
    id: "site-index",
    label: "Site index",
    version: "1.0.40",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/site-index and src/app/site-index",
    rollbackPath:
      "Disable site-index in the feature registry and remove the site-index route, sitemap entry, homepage link, and llms.txt link.",
  },
  {
    id: "launch-readiness-checklist",
    label: "Launch readiness checklist",
    version: "1.0.39",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/launch-readiness and src/app/launch-readiness",
    rollbackPath:
      "Disable launch-readiness-checklist in the feature registry and remove the launch-readiness route, sitemap entry, and homepage link.",
  },
  {
    id: "tax-interaction-pages",
    label: "Tax interaction SEO pages",
    version: "1.0.38",
    layer: "content",
    enabled: true,
    locked: false,
    grayRate: 100,
    ownerArea: "src/content/tax-interaction-pages and src/app/tax-interactions",
    rollbackPath: "Disable tax-interaction-pages in the feature registry and remove tax-interactions routes, sitemap entries, and homepage links.",
  },
];

const featureOverrides = new Map<string, Partial<FeatureRegistryItem>>();

function resolveFeature(id: string): FeatureRegistryItem | undefined {
  const feature = getFeatureById(id);
  const override = featureOverrides.get(id);

  return feature ? { ...feature, ...override } : undefined;
}

export function getFeatureById(id: string): FeatureRegistryItem | undefined {
  return featureRegistry.find((feature) => feature.id === id);
}

export function getEnabledFeatureIds(): string[] {
  return featureRegistry.filter((feature) => isFeatureEnabled(feature.id)).map((feature) => feature.id);
}

export function isFeatureEnabled(id: string): boolean {
  const feature = resolveFeature(id);

  if (!feature) {
    return false;
  }

  if (feature.locked) {
    return true;
  }

  return feature.enabled && feature.grayRate > 0;
}

export function withFeatureOverride<T>(
  id: string,
  override: Partial<FeatureRegistryItem>,
  callback: () => T,
): T {
  const previous = featureOverrides.get(id);
  featureOverrides.set(id, override);

  try {
    return callback();
  } finally {
    if (previous) {
      featureOverrides.set(id, previous);
    } else {
      featureOverrides.delete(id);
    }
  }
}
